### PR TITLE
Fix pending timer issue with `ref.keepAlive()`

### LINKED ISSUE #1941: Widget test fails with pending timers with auto-dispose provider
Hi, I've come across an issue that's making it very hard to write widget tests.

Here's a full example, using 2.1.1:

```dart
final provider1 = Provider.autoDispose((ref) {
  ref.keepAlive();

  ref.watch(streamProvider);
});

final streamProvider = StreamProvider.autoDispose((ref) async* {});

void main() {
  testWidgets('Riverpod test', (tester) async {
    await tester.pumpWidget(
      ProviderScope(
        child: Consumer(
          builder: (context, ref, child) {
            ref.watch(provider1);

            return const SizedBox();
          },
        ),
      ),
    );
  });
}
```

The test fails due to a pending timer created by the scheduler, and `pumpAndSettle()` doesn't fix it.

My understanding of what's going on:

* `UncontrolledProviderScope` is unmounted, resetting the `vsyncOverride`
* `container.disposed()` is called, which then schedules a dispose for the stream controller
* Because that scheduled dispose isn't using `flutterVsync`, a timer is created which isn't cleared up

I haven't been able to find a workaround to this.

Full test output:

```
Pending timers:
Timer (duration: 0:00:00.000000, periodic: false), created:
#0      new FakeTimer._ (package:fake_async/fake_async.dart:308:62)
#1      FakeAsync._createTimer (package:fake_async/fake_async.dart:252:27)
#2      FakeAsync.run.<anonymous closure> (package:fake_async/fake_async.dart:185:19)
#7      _defaultVsync (package:riverpod/src/framework/scheduler.dart:9:3)
#8      _ProviderScheduler._scheduleTask (package:riverpod/src/framework/scheduler.dart:42:10)
#9      _ProviderScheduler.scheduleProviderDispose (package:riverpod/src/framework/scheduler.dart:73:5)
#10     AutoDisposeProviderElementMixin.mayNeedDispose (package:riverpod/src/framework/auto_dispose.dart:40:29)
#11     ProviderElementBase._onRemoveListener (package:riverpod/src/framework/element.dart:894:5)
#12     ProviderElementBase.dispose (package:riverpod/src/framework/element.dart:874:15)
#13     ProviderContainer.dispose (package:riverpod/src/framework/container.dart:656:15)
#14     ProviderScopeState.dispose (package:flutter_riverpod/src/framework.dart:258:15)
#15     StatefulElement.unmount (package:flutter/src/widgets/framework.dart:5105:11)
#16     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1917:13)
#17     ListIterable.forEach (dart:_internal/iterable.dart:39:13)
#18     _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:1926:25)
#19     BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2523:15)
#20     BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2947:7)
#21     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1211:19)
#22     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378:5)
#23     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#24     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104:9)
#25     AutomatedTestWidgetsFlutterBinding.scheduleWarmUpFrame (package:flutter_test/src/binding.dart:1137:5)
#26     runApp (package:flutter/src/widgets/binding.dart:1038:7)
#27     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:848:7)
<asynchronous suspension>
(elided 4 frames from dart:async)

══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test:
A Timer is still pending even after the widget tree was disposed.
'package:flutter_test/src/binding.dart':
Failed assertion: line 1299 pos 12: '!timersPending'

When the exception was thrown, this was the stack:
#2      AutomatedTestWidgetsFlutterBinding._verifyInvariants (package:flutter_test/src/binding.dart:1299:12)
#3      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:857:7)
<asynchronous suspension>
(elided 2 frames from class _AssertionError)

The test description was:
  Riverpod test
════════════════════════════════════════════════════════════════════════════════════════════════════
Test failed. See exception logs above.
```

### PR DESCRIPTION
**Pull request by rrousselGit**
fixes #1941

### CODE REVIEW

File: packages/flutter_riverpod/test/consumer_test.dart [hunk 1]
```diff
@@ -6,6 +6,27 @@ import 'package:flutter_test/flutter_test.dart';
 import 'utils.dart';
 
 void main() {
+  testWidgets('Riverpod test', (tester) async {
+    final streamProvider = StreamProvider.autoDispose((ref) async* {});
```
Comment (rrousselGit) [inline packages/flutter_riverpod/test/consumer_test.dart:10]:
```suggestion
    // Regression test for https://github.com/rrousselGit/riverpod/pull/3156

    final streamProvider = StreamProvider.autoDispose((ref) async* {});
```
